name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Se ejecuta cuando hagas push a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

      # 4️⃣ Construir documentación
      - name: Build docs
        run: |
          cd docs
          python -m sphinx -b html source build/html

      # 5️⃣ Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          branch: gh-pages
          force_orphan: true
          keep_files: false
